#endswith()
str1 = "i am studying in aktu"
print(str1.endswith("tu"))
print(str1.endswith("in"))
#capatilize() --> fisrt word of string
print(str1.capitalize())
print(str1)
str1 = str1.capitalize()
print(str)
#replace(old,new)
print(str1.replace("aktu","IIT Bombay"))
#find()
print(str1.find("s"))
print(str1.find("in"))
#count()
print(str1.count("m"))